### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/install-media#20]
A few users with Realtek ethernet hardware reported that they could not connect to the network from the installer.

Once installed using phone tethering as a work-around, networking worked, but did not work in the installer.

**Comment by rshamsnejad** [comment]
Would it be possible to include as much firmware as possible in the installer, and use `wifi-menu` or something similar ? Then if a `wlan` is detected, a prompt for Wifi connection would be triggered

**Comment by moonwolf-github** [comment]
Maybe my https://github.com/gamer-os/gamer-os/issues/139 is related.

**Comment by moonwolf-github** [comment]
Unfortunately in my case after installation network still doesn't work.

**Comment by eggprez** [comment]
I have having the same issue (Z490i). Any update to the installer would be greatly appreciated!

**Comment by LuRsT** [comment]
For people asking about wireless support, I managed to install it by building a gamer-os image with the following packages and then running [`iwctl`](https://wiki.archlinux.org/index.php/Installation_guide) to get network working and then running the install script afterwards. I made a PR with those packages: https://github.com/gamer-os/install-media/pull/26

**Comment by EdvinLndh** [comment]
I'm also having a bit of a struggle connecting during installation. 
Ethernet controller: Qualcomm Atheros Killer E220x Gigabit

**Comment by LuRsT** [comment]
@EdvinLndh Did you try my suggestion above?

**Comment by Samsagax** [comment]
Is this issue still relevant with latest install-media?
