### ISSUE TITLE
failed retrieving file 'chimeraos.db' from disk

### ISSUE THREAD

**Issue by aleksasiriski** [ChimeraOS/install-media#42]
also 'install-media/output/*.iso': No such file or directory

**Comment by Samsagax** [comment]
Seems that archiso failed early along the build script. Could you check that?

**Comment by aleksasiriski** [comment]
Well yes, there's no chimeraos.db file in the repo so it can't sync repositories with pacman.

**Comment by alkazar** [comment]
What are you trying to do? What command did you run?

**Comment by aleksasiriski** [comment]
`./build-iso.sh`

I'm on arch with all dependencies installed...

**Comment by Samsagax** [comment]
> `./build-iso.sh`
> 
> I'm on arch with all dependencies installed...

The `chimeraos.db` file and repository are created as part of the build process. There must be an error prior to what you described.

**Comment by alkazar** [comment]
I fixed a few issues with the build recently. Perhaps try again?
The Github build is working successfully now.

I wonder what it is you are trying to accomplish by manually building the ISO?

**Comment by aleksasiriski** [comment]
> I wonder what it is you are trying to accomplish by manually building the ISO?

I want to change a few packages and configs, for example to use linux-zen over standard kernel and also to add spotifyd.

**Comment by aleksasiriski** [comment]
[Here](https://www.toptal.com/developers/hastebin/nixekaveva.sql)'s the full log of command `sudo bash build-iso.sh`

**Comment by alkazar** [comment]
Strange, looks like the build for `frzr` package was successful but it can't find the file.

In any case, the build is working in GitHub.

Creating a custom build of the installer is not going to help you create a custom installation of ChimeraOS. You need to fork and customize this repo: https://github.com/ChimeraOS/chimeraos
