### ISSUE TITLE
Wi-fi dialog can't be read or won't function on the Aya Neo 2 screen

### ISSUE THREAD

**Issue by TAGE7** [ChimeraOS/install-media#51]
Currently on 2023-03-28 (d13bf66) installer, the wi-fi dialogue isn't legible which means users are unable to proceed unless they use an external screen.

This is part of another bug with the display being sidewayz on the AN2 screen, but this is a hardware issue so I'm not sure if there's a work around.

The work around for no wifi dialog showing up is to use an external monitor via an HDMI adapter or wired network to skip through the internet access dialog

**Comment by alkazar** [comment]
Can you post a screenshot/photo? It is legible for me, it is just rotated.
